/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
export const PROMPT_CATEGORIES = {
  '🕰️ Vintage & Classic': [
    '1920s New Orleans Jazz',
    '1930s Swing Big Band',
    '1940s Bebop Quartet',
    '1950s Cool Jazz Trio',
    'Delta Blues Slide Guitar',
    '1940s Jump Blues',
    '1950s Chicago Blues',
    'Smoky Film Noir Saxophone',
    'Brazilian Bossa Nova Guitar',
    'Sultry Bossa Nova Vocals',
    'Argentine Tango Accordion',
    'Dramatic Tango Orchestra',
    'Vintage Vinyl Crackle',
    'Upright Bass Solo',
  ],
  '🎹 Impressionist & Minimal': [
    'Satie Gnossienne Piano',
    'Satie Gymnopedie Mood',
    'Minimalist Impressionist Piano',
    'Melancholic Parisian Cafe Piano',
  ],
  '🎛️ Effects & Production': [
    'Gated Reverb',
    'Sidechained Bass',
    'Tape Saturation',
    'Wide Stereo Image',
    'Parallel Compression',
    'Flanged Vocals',
    'Glitchy Granular Delay',
    'High-Pass Filter Sweep',
    'Ducking Synth Pads',
    'Multi-tap Ping Pong Delay',
    'Crushed to Hell',
    'Ghost Delay',
    'Mono Crusher',
    'Feedback Bloom',
    'Stutter Mode',
    'Reverb Cathedral',
    'Sizzle Shelf',
    'Bassy Mudslide',
    'Sidechain Abyss',
    'Nasal Boost',
  ],
  '💅 Pure Vibe': [
    'Kiss Me in the Chorus',
    'Too Much Compression, Babe',
    'Velvet Machine Gun',
    'Spiritual Mod Wheel',
    'The Sad Girl Fader',
    'Dreams You Forgot to Save',
    'Wet & Widescreen',
    'Almost Famous',
    'Final Song Before the UFOs Come',
    'Nightclub in a Haunted Modem',
  ],
  'Instruments & Rhythms': [
    'Lush Strings',
    'Strummed Acoustic Guitar',
    'Slap Bass',
    '80s Synth Bass',
    'Amen Break',
    'Hip Hop Beat',
    '808',
    '909',
    'Muted Trumpet',
    'Saxophone',
    'Vibraphone',
    'Electric Piano',
    'Chiptune',
    'Steel Drum',
    'Kalimba',
    'Hand Pan',
  ],
  'Genres & Styles': [
    'Chicago Hard House',
    'Juke',
    'Footwork',
    'Ghettotech',
    'Detroit Witch House',
    '1990s Detroit Techno',
    '1990s Midwest Rave',
    'Early Rave Hardcore',
    'Early 90s UK Hardcore',
    '311 Style Reggae',
    'Braindance',
    'Skweee',
    'Glitch Hop',
    'Wonky',
    'Clickhop',
    'Microsound',
    'Max/MSPcore',
    'Post-IDM',
    'Terrorcore',
    'Splittercore',
    'Breakcore',
    'Extratone',
    'Speedcore',
    'Industrial Hardcore',
    'Noisecore',
    'Crossbreed',
    'Deep Trancecore',
    'Dreampunk',
    'Ambient Jungle',
    'Lowercase Techno',
    'Chillgressive',
    'Hypnagogic Pop',
    'Nightcore',
    'Witch House',
    'Hardvapour',
    'Slushwave',
    'Mallsoft',
    'Phonk',
    'Shitcore',
    'Furry House',
    'Tiktokcore',
    'Simpsonwave',
    'Lolicore',
    'Jungle Tekno',
    'Vaportrap',
    'Mákina',
    'Zheani-core',
    'Moombahcore',
    'Crunkstep',
    'Neurohop',
    'Baroque Dubstep',
    'Dungeon Synthstep',
  ],
  'Artist & Album Styles': [
    'Early KMFDM',
    'Early Ministry',
    'Ministry',
    'Nirvana - Nevermind',
    'Nirvana - Bleach',
    'Beck - Stereopathetic Soulmanure',
    'Beck - Odelay',
    'Madonna - Like a Prayer',
    'Del Shannon - Runaway',
    'Like a Prayer Glow',
    'Runaway Breakdown',
    'Aphexic Dribble',
    'Prince Snare Tight',
    'Blondie at CBGBs',
    'Boards of Canada VHS Melt',
    'Missy Elliott Timbaland',
    'Del Shannon Highway Ghost',
    'Satie from the Crypt',
    'Phil Collins Reverb Button',
  ],
  'Mood / Emotion': [
    'Longing in Stereo', 'Vengeful Joy', 'Glassy Resignation', 'Playful Despair', 'Euphoric Collapse', 'Tender Recoil', 'Melancholy Reload', 'Blushcore', 'Horny but Abstract',
  ],
  '🌀 Texture / Timbre': [
    'Dusty Circuits', 'Saturated Ribbon', 'Sticky Filters', 'Crushed Velvet Noise', 'Oil-Slick Pads', 'Chrome Reverberation', 'Tape-Warp Echo', 'Hollow Plastic Dreams', 'Sharp but Wet',
  ],
  '🗺️ Imagined Places / Worlds': [
    'Miami Rainstorm 1986', 'Tokyo Rooftop at Dawn', 'Abandoned Mall Jungle', 'Venusian Jazz Lounge', 'Chicago Alley Bass Ritual', 'Desert Bus Rave', 'Basement LAN Party', 'Arctic Echo Chamber', 'Saturn’s Softside',
  ],
  '🔬 Techniques / Theoretical Ideas': [
    'Bitcrush Heaven', 'Infinite Sustain', 'LFO Entanglement', 'Modal Drift', 'FM Whisper Stack', 'Reverse Everything', 'Polyrhythm Cascade', 'One Note Loop', 'Just Add Glitch',
  ],
  '📼 Cultural / Aesthetic Tags': [
    'VHS Rec Room', 'Cyber Pagan', 'Skatepark Ambience', 'Pinkpunk', 'AI Diva', 'Tumblr Witch', 'Digital Goth Milk', 'Algorithmic Soul', 'Cursed Vapor',
    'Italo K-Hole',
    'Miami Mallcore',
    'Detroit Gospel Machine',
    'Anime Beachcore',
    'Chicago Footwerk Ritual',
    'French Filter Disco',
    'Haunted Dub Temple',
    'Breakcore Sorbet',
    'Rust Belt Cyberpop',
    'Trucker Ambient',
    'Y2K Trance',
    'Cybergrind',
    'Terminal Chill',
    'HexD',
    'Seapunk',
    'Scenecore',
    'Ravewave',
    'Goblincore Techno',
  ],
  '🔮 Archetype / Narrative Hooks': [
    'The Hacker’s Funeral', 'Lover’s Ghost Mix', 'Last Broadcast Before Impact', 'Escape Pod Anthem', 'The Algorithm Fell In Love', 'Childhood Memory of a Synth That Never Existed', 'Bootleg Angel Choir', 'Dystopia with Hope', 'You’re the Villain Now',
  ],
};

export const ALL_PROMPTS = Object.values(PROMPT_CATEGORIES).flat();